# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: '^\.specstory/'
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
            args: ['--maxkb=750']
          - id: check-ast
          - id: check-json
          - id: check-toml
          - id: check-yaml
          - id: detect-private-key
          - id: fix-byte-order-marker
          - id: mixed-line-ending
          - id: name-tests-test

    - repo: https://github.com/astral-sh/uv-pre-commit
      # uv version.
      rev: 0.7.19
      hooks:
          # Update the uv lockfile
          - id: uv-lock

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.12.1 # Updated to match pyproject.toml ruff version
      hooks:
          - id: ruff
            name: ruff (lint, autoflake, isort, flake8, bandit, etc)
            args:
                - --fix
                - --unsafe-fixes
          - id: ruff-format
            name: ruff (black formatting)
    # Plugins Ruff cannot replace
    - repo: https://github.com/PyCQA/doc8
      rev: v1.1.1
      hooks:
          - id: doc8
            args: ["--max-line-length=112", "--file-encoding=utf-8"]

    # - repo: https://github.com/streetsidesoftware/cspell-cli
    #   rev: v9.0.1
    #   hooks:
    #       - id: cspell # Spell check changed files
    #       - id: cspell # Spell check the commit message
    #         name: check commit message spelling
    #         args:
    #             - --no-must-find-files
    #             - --no-progress
    #             - --no-summary
    #             - --files
    #             - .git/COMMIT_EDITMSG
    #         stages: [commit-msg]
    #         always_run: true # This might not be necessary.
